### ISSUE TITLE
How I can implement Multi-QuoteProcessor?

### ISSUE THREAD

**Issue by M4Lien** [renanbr/bibtex-parser#58]
Hi renabr!
I am using your bibtex-parser. I've got bibtex file through sciencedirect, but it was invalid bib.
so I've reviewed the bibtex file. That file contains multi-quote. I guess it is the issue.
therefore, I am trying to implement quoteProcessor, so I need your help.

**Comment by renanbr** [comment]
Hi @M4Lien,

Processors can process entries only, because they are called by the Listener **after** parsing is done.

Here a summary of the internal mechanism:

- Parser:
    - works like a tokenizer;
    - is responsible for finding units;
    - sends units to the Listener on the fly[1];
    - does **not** send invalid units to the Listener[2].
        - in other words, it throws an exception as it founds an unexpected char[3];
        - a char is checked against the chars already found in the streaming[4].
- Listener:
    - receives valid units found by the Parser;
    - packs these units in a list of entries;
    - then calls attached processors.
- Processor:
    - is attached to the Listener, not to the Parser;
    - traits entire and valid (lexically and syntactically) entries.

[1, 3, 4] If I understood your suggestion, what you want is viable/possible by changing these parser's behaviours, not via Processor.

[2] In the case mentioned in #57, the char `q` after a `"` (in this case it's closing a text content) is not recognized as a valid sequence.

**Comment by renanbr** [comment]
https://github.com/renanbr/bibtex-parser/issues/48#issuecomment-742098818
