### ISSUE TITLE
Unexpected character '\0' at line 19 column 2

### ISSUE THREAD

**Issue by boopr** [renanbr/bibtex-parser#6]
I'm trying to parse a bibtex using your library, but I'm getting the following error : 

```
Unexpected character '\0' at line 19 column 2
```

Any way to support the null character ?  
Thanks 😄

**Comment by renanbr** [comment]
> Any way to support the null character ?

I don't know what the '\0' character means in the latex world, but I think we could support it :+1:

Could you share the entry you are trying to parse?

**Comment by boopr** [comment]
Yes ! The bibtex is available at [this address](http://www.sciencedirect.com/science/article/pii/S1076633216303956).

**Comment by renanbr** [comment]
I should review my internet skills :sweat_smile: I can't find the export button, maybe because i'm not logged in, I've found just a link to export to the `.ris` format

@boopr is there other way I can download it or could you send it to my inbox?

**Comment by renanbr** [comment]
Thanks for sharing the file.

The error is caused because when the parser find a `%` character inside a delimited-value section, it thinks that a comment section is starting. This causes that all characters after the `%` is ignored, including the quote that closes the delimited-value section, which causes a unexpected end of file. The message error is not very clear, I agree.

I won't have time to get down to reviewing soon, but I've opened a [branch for this issue](https://github.com/renanbr/bibtex-parser/tree/issue-6-unexpected-null-char).

Some notes:

- In latex the `%` char should be escaped as `\%`, but It makes sense not to do it in a bibtex file
- The [§4, item 14, p. 14](http://mirror.ibcp.fr/pub/CTAN/biblio/bibtex/base/btxdoc.pdf) of official documentation says : "LATEX's comment character '%' is not a comment character in the database files."
  - It means this library does not work strictly
  - I'm not sure whether we should keep the `%` as comment character in the stable version or not ([some libraries do the same](https://www.google.com/search?q=bibtex%20comment))
- The [error in travis for PHP 7](https://travis-ci.org/renanbr/bibtex-parser) is not related to the fix
